### ISSUE TITLE
Props and state anti-patterns

### ISSUE THREAD

**Issue by KCraw** [project-gustave/gustave-client#20]
Putting this up as a general reminder for React...

1. this.props is always passed in from parent components and should be treated as immutable
2. this.state and setState() should be used for state used in a render
3. this.{x} should be used for state that is not part of a render
4. Using props to set state, including computed state, is an anti-pattern unless the prop is explicitly and exclusively used to set an initial default state (and intentionally does not stay in sync with current state)

https://facebook.github.io/react/tips/props-in-getInitialState-as-anti-pattern.html

**Comment by KCraw** [comment]
For default state....

1. Use defaultProps = {...}; rather than checking for props yourself

**Comment by jimbol** [comment]
Good call!  Definitely point this out when we're doing this in the code (I can think of a few I've done).

**Comment by KCraw** [comment]
One frustration I have with React is that it relies heavily on an object model, but is doing its best to implement functional reactive programming inside that model. Sometimes that causes paradigm confusion (at least for me), but I think FB is right on why it should be done this way.
